#!/usr/bin/env bash
#
# scripts/setup_notebooklm.sh - Interactive wizard for NotebookLM & Gemini authentication.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit it.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0
_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  This wizard guides you through setting up Google NotebookLM or\n' "$DIM"
  printf '  Gemini synthesis credentials on a remote headless Linux machine.\n'
  printf '  Values will be safely written to %s.%s\n\n' "$ENV_FILE" "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ URL:%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview      >/dev/null 2>&1; then wslview "$url";
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url";
    elif command -v xdg-open     >/dev/null 2>&1; then xdg-open "$url";
    elif command -v open         >/dev/null 2>&1; then open "$url";
    fi
  } >/dev/null 2>&1 || true
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} )) && note "Wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

banner "NotebookLM & Synthesis Gateway Credentials Setup"

# ── Stage 1: Choose Backend Strategy ───────────────────────────────────────
stage "Choose Authentication Method"
say "Because this Linux server has no graphical browser, choose how you wish"
say "to authenticate your NotebookLM synthesis gateway:"
say ""
say "  1) Official Google Gemini API Key (Fastest, zero-maintenance, 100% stable)"
say "     - Generates an API key from Google AI Studio in 10 seconds."
say "     - Direct official API: no session cookies or master token rotations."
say ""
say "  2) Persistent Android Master Token JSON (Durable, portable single-line)"
say "     - Generated on your local PC via \`notebooklm login --master-token\`"
say "     - Paste the resulting JSON text here; wizard compresses it into 1 line."
say ""
say "  3) Web Session Cookies (Desktop Chrome/Edge DevTools)"
say "     - Copy \`__Secure-1PSID\` and \`__Secure-1PSIDTS\` from browser DevTools."
say ""

CHOICE=""
while [[ ! "$CHOICE" =~ ^[123]$ ]]; do
  printf '  %sSelect option [1, 2, or 3]:%s ' "$BOLD" "$RESET"
  read -r CHOICE || true
done

# ── Stage 2: Capture Credentials ───────────────────────────────────────────
stage "Configure Credentials"

if [[ "$CHOICE" == "1" ]]; then
  say "You selected: Official Google Gemini API Key."
  say "Open Google AI Studio in your browser on your computer:"
  open_url "https://aistudio.google.com/app/apikey"
  say ""
  step "Click 'Create API key' in Google AI Studio and copy it."
  ask_secret GEMINI_KEY "Paste your GEMINI_API_KEY:"
  if [[ -n "$GEMINI_KEY" ]]; then
    write_env "GEMINI_API_KEY" "$GEMINI_KEY"
  else
    warn "No key entered, skipped."
  fi

elif [[ "$CHOICE" == "2" ]]; then
  say "You selected: Android Master Token (Single-line JSON)."
  say "On your local laptop/desktop (with Python installed):"
  step "Run: pip install notebooklm-py"
  step "Run: notebooklm login --master-token --account your_email@gmail.com"
  step "Open the generated master_token.json or copy its contents."
  note '  Example content: {"account":"user@gmail.com","master_token":"aas_xxx"}'
  say ""
  say "  Paste the JSON below (multi-line is supported!)."
  say "  When finished pasting, press [Ctrl+D] (or Enter then Ctrl+D) to submit:"
  printf '\n'

  CLEAN_JSON=""
  if CLEAN_JSON=$(python3 -c '
import sys, json
try:
    content = sys.stdin.read().strip()
    if not content:
        sys.exit(0)
    data = json.loads(content)
    print(json.dumps(data))
except Exception as e:
    sys.stderr.write(f"Error parsing JSON: {e}\n")
    sys.exit(1)
'); then
    if [[ -n "$CLEAN_JSON" ]]; then
      # Also save to standard master_token.json file
      mkdir -p "$HOME/.notebooklm/profiles/default"
      echo "$CLEAN_JSON" > "$HOME/.notebooklm/profiles/default/master_token.json"
      chmod 600 "$HOME/.notebooklm/profiles/default/master_token.json"
      say "  ✓ Saved to ~/.notebooklm/profiles/default/master_token.json"

      write_env "NOTEBOOKLM_AUTH_JSON" "'$CLEAN_JSON'"
      write_env "NOTEBOOKLM_BACKEND" "android"
    else
      warn "Empty input received, skipped."
    fi
  else
    warn "Invalid JSON format. Please ensure valid JSON was pasted."
  fi

elif [[ "$CHOICE" == "3" ]]; then
  say "You selected: Desktop Browser Session Cookies."
  say "On your computer's browser where you are logged into NotebookLM:"
  open_url "https://notebooklm.google.com"
  step "Press F12 to open Developer Tools -> Application / Storage -> Cookies."
  step "Find and copy the value of cookie '__Secure-1PSID'."
  ask_secret COOKIE_1PSID "Paste __Secure-1PSID:"
  step "Find and copy the value of cookie '__Secure-1PSIDTS'."
  ask_secret COOKIE_1PSIDTS "Paste __Secure-1PSIDTS:"

  COOKIES_PAYLOAD="{\"cookies\":{\"__Secure-1PSID\":\"$COOKIE_1PSID\",\"__Secure-1PSIDTS\":\"$COOKIE_1PSIDTS\"}}"
  write_env "NOTEBOOKLM_AUTH_JSON" "'$COOKIES_PAYLOAD'"
  write_env "NOTEBOOKLM_BACKEND" "web"
fi

# ── Stage 3: Verification & Doctor Diagnostic ──────────────────────────────
stage "Verification & Doctor Diagnostic"
say "Running system diagnostic to verify credentials and connectivity..."
say ""

if PYTHONPATH=src python3 -m research_toolkit.cli doctor; then
  say ""
  printf '  %s✓ Diagnostic passed!%s\n' "$GREEN" "$RESET"
else
  warn "Diagnostic returned warnings. Please inspect the table above."
fi

pause "Press Enter to finish setup"

finish
